USE sgq-quality-compliance;

CREATE TABLE DEPARTAMENT (
  ID_DEPARTAMENT BIGINT NOT NULL,
   DES_DEPARTAMENT VARCHAR(255) NULL,
   DES_LOCATION VARCHAR(255) NULL,
   DT_CREATION DATETIME NOT NULL,
   DT_UPDATE DATETIME NULL,
   CONSTRAINT PK_DEPARTAMENT PRIMARY KEY (ID_DEPARTAMENT)
);

CREATE TABLE NON_COMPLIANCE (
  ID_NON_COMPLIANCE BIGINT NOT NULL,
   DES_NON_COMPLIANCE VARCHAR(255) NULL,
   DES_OPERATIONAL_CONSEQUENCE VARCHAR(255) NULL,
   DES_TYPE VARCHAR(255) NULL,
   DT_CREATION DATETIME NOT NULL,
   DT_UPDATE DATETIME NULL,
   CONSTRAINT PK_NON_COMPLIANCE PRIMARY KEY (ID_NON_COMPLIANCE)
);

CREATE TABLE PART (
  ID_PART BIGINT NOT NULL,
   DES_NAME VARCHAR(255) NULL,
   DES_MODEL VARCHAR(255) NULL,
   NUM_SERIAL_NUMBER BIGINT NULL,
   DT_CREATION DATETIME NOT NULL,
   DT_UPDATE DATETIME NULL,
   CONSTRAINT PK_PART PRIMARY KEY (ID_PART)
);

CREATE TABLE VEHICLE (
  ID_VEHICLE BIGINT NOT NULL,
   DES_NAME VARCHAR(255) NULL,
   DES_MODEL VARCHAR(255) NULL,
   DT_RELEASE DATETIME NULL,
   DT_CREATION DATETIME NOT NULL,
   DT_UPDATE DATETIME NULL,
   CONSTRAINT PK_VEHICLE PRIMARY KEY (ID_VEHICLE)
);

CREATE TABLE ROLE (
  ID_ROLE BIGINT NOT NULL,
   DES_NAME VARCHAR(255) NULL,
   DT_CREATION DATETIME NOT NULL,
   DT_UPDATE DATETIME NULL,
   CONSTRAINT PK_ROLE PRIMARY KEY (ID_ROLE)
);

CREATE TABLE PROFILE (
  ID_PROFILE BIGINT NOT NULL,
   DES_PROFILE VARCHAR(255) NULL,
   DT_CREATION DATETIME NOT NULL,
   DT_UPDATE DATETIME NULL,
   CONSTRAINT PK_PROFILE PRIMARY KEY (ID_PROFILE)
);

CREATE TABLE USER (
  ID_USER BIGINT NOT NULL,
   DES_NAME VARCHAR(255) NULL,
   DES_EMAIL VARCHAR(255) NULL,
   DES_DOCUMENT VARCHAR(255) NULL,
   DES_PHONE VARCHAR(255) NULL,
   DES_GENRE VARCHAR(255) NULL,
   ID_ROLE BIGINT NULL,
   ID_DEPARTAMENT BIGINT NULL,
   DT_CREATION DATETIME NOT NULL,
   DT_UPDATE DATETIME NULL,
   CONSTRAINT PK_USER PRIMARY KEY (ID_USER)
);

ALTER TABLE USER ADD CONSTRAINT FK_USER_ON_ID_DEPARTAMENT FOREIGN KEY (ID_DEPARTAMENT) REFERENCES DEPARTAMENT (ID_DEPARTAMENT);

ALTER TABLE USER ADD CONSTRAINT FK_USER_ON_ID_ROLE FOREIGN KEY (ID_ROLE) REFERENCES `ROLE` (ID_ROLE);

CREATE TABLE USER_PROFILE (
  ID_PROFILE BIGINT NOT NULL,
   ID_USER BIGINT NOT NULL,
   CONSTRAINT PK_USER_PROFILE PRIMARY KEY (ID_PROFILE, ID_USER)
);

ALTER TABLE USER_PROFILE ADD CONSTRAINT FK_USEPRO_ON_PROFILE_ENTITY FOREIGN KEY (ID_PROFILE) REFERENCES PROFILE (ID_PROFILE);

ALTER TABLE USER_PROFILE ADD CONSTRAINT FK_USEPRO_ON_USER_ENTITY FOREIGN KEY (ID_USER) REFERENCES USER (ID_USER);

CREATE TABLE NON_COMPLIANCE_ACTION (
  ID_NON_COMPLIANCE_ACTION BIGINT NOT NULL,
   DES_IMMEDIATE_ACTION VARCHAR(255) NULL,
   DES_FOLLOW_UP_ACTION VARCHAR(255) NULL,
   DT_DUE_DATE DATETIME NULL,
   ID_NON_COMPLIANCE BIGINT NULL,
   DT_CREATION DATETIME NOT NULL,
   DT_UPDATE DATETIME NULL,
   CONSTRAINT PK_NON_COMPLIANCE_ACTION PRIMARY KEY (ID_NON_COMPLIANCE_ACTION)
);

ALTER TABLE NON_COMPLIANCE_ACTION ADD CONSTRAINT FK_NON_COMPLIANCE_ACTION_ON_ID_NON_COMPLIANCE FOREIGN KEY (ID_NON_COMPLIANCE) REFERENCES NON_COMPLIANCE (ID_NON_COMPLIANCE);

CREATE TABLE INCIDENT (
  ID_INCIDENT BIGINT NOT NULL,
   DES_INCIDENT VARCHAR(255) NULL,
   DES_STATUS VARCHAR(255) NULL,
   DES_TYPE VARCHAR(255) NULL,
   DES_PLACE VARCHAR(255) NULL,
   DES_DEMAGE VARCHAR(255) NULL,
   ID_PART BIGINT NULL,
   ID_VEHICLE BIGINT NULL,
   ID_NON_COMPLIANCE BIGINT NULL,
   ID_USER BIGINT NULL,
   DT_CREATION DATETIME NOT NULL,
   DT_UPDATE DATETIME NULL,
   CONSTRAINT PK_INCIDENT PRIMARY KEY (ID_INCIDENT)
);

ALTER TABLE INCIDENT ADD CONSTRAINT FK_INCIDENT_ON_ID_NON_COMPLIANCE FOREIGN KEY (ID_NON_COMPLIANCE) REFERENCES NON_COMPLIANCE (ID_NON_COMPLIANCE);

ALTER TABLE INCIDENT ADD CONSTRAINT FK_INCIDENT_ON_ID_PART FOREIGN KEY (ID_PART) REFERENCES PART (ID_PART);

ALTER TABLE INCIDENT ADD CONSTRAINT FK_INCIDENT_ON_ID_USER FOREIGN KEY (ID_USER) REFERENCES USER (ID_USER);

ALTER TABLE INCIDENT ADD CONSTRAINT FK_INCIDENT_ON_ID_VEHICLE FOREIGN KEY (ID_VEHICLE) REFERENCES VEHICLE (ID_VEHICLE);